spring.application.name=credit-risk-service
gemini.api.key=AIzaSyB9OOcsXXvJ_XRpWCHV4IEMvWgoFALhs8A
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent

server.port=${PORT:8080}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.config.import=optional:env

